# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pushlished_date',
            new_name='published_date',
        ),
    ]
